### ISSUE TITLE
'morphology_file' should be a filename w/o extension

### ISSUE THREAD

**Issue by arsenius7** [AllenInstitute/sonata#4]
As the spec states now, `morphology_file` is
> The name of the SWC file (potentially, with the path) containing the morphology for a given node or node type.

IMHO, using full paths for morphology file should be discouraged to facilitate relocating the circuit.
Specifying file extension also seems to be excessive.

**Comment by arsenius7** [comment]
Actually, if it is a filename w/o path and extension, maybe we can drop '_file' suffix as well.

**Comment by hernando** [comment]
I'm not sure, `morphology` alone could be also be understood as the morphology type, I'd rather keep file to disambiguate, but I don't have strong opinion.

**Comment by wvangeit** [comment]
if the extension is dropped, how do we know which extension to use (i.e. where is that info ?) ?

**Comment by hernando** [comment]
I would make that modification when the time comes and live it as it is for the moment. The preferred extension could also be added as a field in the circuit_config.json rather than a column in the nodes.h5.

**Comment by wvangeit** [comment]
I wouldnt put it in the circuit_config.json because that won't allow for mixing of morphology formats.
We dont need to add it now if not necessary, I guess we can always add something later in the trend of 'if column empty, assume swc'.
Just find it a bit of a pity that we have to hardcode the morphology format in the simulator code.

**Comment by hernando** [comment]
Closing as we won't make further changes for the moment.
