### ISSUE TITLE
What are units of amp in IClamp?

### ISSUE THREAD

**Issue by pgleeson** [AllenInstitute/sonata#42]
They seem to be in nA here: https://github.com/AllenInstitute/sonata/blob/master/examples/5_cells_iclamp/simulation_config.json#L31
but pA here (I realise this is not an "official" Sonata example): https://github.com/AllenInstitute/bmtk/blob/develop/docs/examples/point_iclamp/config.json#L30

**Comment by kaeldai** [comment]
We have been discussing this and it seems related to issue #66. I can fix it so that the PointNet example (which uses NEST) uses the same units of measures as the examples built on top of NEURON - but that would require agreeing to a default way of representing units. Closing this and will fix the issue depending on the outcome of the other one.
