### ISSUE TITLE
Group labeled '0' in nodes and edges hdf5 files

### ISSUE THREAD

**Issue by salvadord** [AllenInstitute/sonata#49]
E.g. cortex_nodes.h5 has structure nodes.cortex.0.x and excvirt_cportex_edges.h5 has edges.excvirt_to_cortex.0.syn_weight

What does that '0' correspond to ? Will other datasets have additional numbers... '1', '2', etc?

Sorry if I'm missing something obvious in the structure or the way hdf5 works.

**Comment by hernando** [comment]
That 0 is a node group and as you guessed there could be others. In the population level datasets, you may have noticed one called node_group_id. This datasets points to the node group to which each node belongs. Notice that node_group_id, node_id and node_group_index are not guaranteed to be sorted in any way or exhaustive (from 0 to n). These two features of the spec allow maximum flexibility, but admittedly they complicate implementations. From our side we have been

**Comment by hernando** [comment]
It doesn't seem to be the case in the repository. Which makes me raise (again) the question: @kaeldai, @CellAssembly  do we really need groups? Can't we simply use populations and therefore remove the node_group_index and node_group_id datasets?

**Comment by kaeldai** [comment]
One of the issues is that if you split every group into different populations, the number of edge population/files grows exponentially. For example in our models some cells have unique orientation and some don't. Some cells have tuning angle and some don't. So our nodes files may typically have between 2 to 4 different "node_groups". And I can imagine it getting even worse. But no matter how many "node_groups" we have we only need one set of edges for recurrent connections. If we broke them up into different populations we'd need anywhere between 4 to 16 different edge populations.

Another advantage that works for our use-cases is that "node_groups" let's us separate network topology from implementation of each cell. You can change the "node_group_id" and/or "node_type_id" for an individual cell to change parameters or convert it from one type to another, while still maintaining all the incoming/outgoing edges. I know this doesn't work or may even break other implementations, but for us it's provided a big benefit because we can build a network once and run it across different models and levels-of-resolution.

That said I think there has to be a better way of representing the nodes without drastically affecting the edges. But at this point I'm not sure how?

**Comment by salvadord** [comment]
@kaeldai can you point to an example with multiple node_groups so I can test this? thx

**Comment by kaeldai** [comment]
The internal_nodes.h5 in this example has two node-groups:
https://github.com/AllenInstitute/bmtk/tree/develop/docs/examples/bio_450cells_exact/network

This network has two model_types - biophysical and intfire1. The biophysical cells (node_group 0) have angles of rotations while that point (node_group 1) don't.
