### ISSUE TITLE
Node_types.csv with non-homogenoues node types

### ISSUE THREAD

**Issue by hernando** [AllenInstitute/sonata#9]
The spec states that there's a 1 to 1 mapping between node and node types files which is given by the network config json file. Since inside a population we allow nodes with different attribute sets (it's at the group level where nodes are homogeneous) and the node types files is the same for all the population, it means that some columns in the csv may not apply to all model types.
In the example provided by @kaeldai by e-mail, the point_process types contain the value NONE for some of the columns due to this issue. The spec should document what to do in this cases.
In any case, it also looks wrong having to leave values undefined. For a future revision it should be reconsidered whether the node_types file should be a csv or a json with a separate dictionary per node type (even if attribute keys need repetition)

**Comment by kaeldai** [comment]
I agree that forcing a one-to-one mapping between nodes.h5 and node_types.csv is not the ideal way. I understand that for some use cases it would be better to split the node_types.csv into multiple files with only relevant columns as long as node_type_id's are unique. That would require changing the "nodes" block in the network config - but working on implementation I'm starting to think the entire "network" block needs to be refactored (especially since we allow multiple populations per file).

However I don't have an issue with non-homogeneous node types and think having NONE's is okay. One thing we like to do is to change a population type and rerun the simulation. So if a user wants to change a subset of cells from biophysical to point they would need to set the morphology to NONE in a text editor.

**Comment by arsenius7** [comment]
>  Since inside a population we allow nodes with different attribute sets (it's at the group level where nodes are homogeneous) and the node types files is the same for all the population, it means that some columns in the csv may not apply to all model types.

For me it sounds like yet another argument in favor of homogeneous nodes per h5 (instead of duplicating the hierarchy levels in both h5 and associated node types dictionary).

**Comment by hernando** [comment]
The reason for allowing multiple groups per is population is based on the assumption that having a unique population id for all nodes in the groups reduces the potential combinatorial explosion of edge files connecting groups (as edge files have target and source populations, not groups). I'm not sure whether this combinatorial explosion is a real concern, but it was agreed to have this additional level to avoid it.
If I remember correctly, the ABI people also wants to be able to change the proportion of cells using biophysical and point neuron models by moving cells from one set to another without disturbing the edges files. I'm not sure how this works in practice because when you have two biophysical cells, you want to connect them with multiple edges to represent all the synapses, so you would need to change the edges file everytime you change the composition of the groups anyway.

I think that only when we have played enough with the file format we can realize what't the best design for the next version.

**Comment by arsenius7** [comment]
To give the discussion some specifics, can we have an example where all these levels for nodes and edges are justified (full set of files, I mean)? Should I refer to the circuit @kaeldai provided as such an example?

I have not played enough with it, maybe, but in my eyes the potential "combinatorial explosion" of number of files is instead moved to "combinatorial exposion" of the specification itself, where to fetch node properties for a given edge I have to:
- refer to an attribute of `source_node_id`
- consult with network config to find corresponding nodes H5 file and population (how?)
- consult `node_group_id' and `node_group_index` inside that population

...and in the end I find that I lost my way in broad daylight trying to keep simultaneously in my mind "edges" dict in circuit config, edge H5 file, edge types CSV file, edge population, edge group, their node counterparts and the way the two are joined together.

I also don't really grasp how can we hot-swap one node group with another w/o affecting the edges.

**Comment by kaeldai** [comment]
We use the node_types and edge_types to adjust cell properties between simulations. We can even switch between using biophysical to point neuron models for a large subset of cells by just modifying a few columns in the csv. You may have to adjust the edge_types file also. But in general we prefer to modify a couple of csv files in a text editor rather than regenerating/updating the entire network. One of our goals is to study the same network models across different levels of resolution and the node/edge types has proven really powerful for this.
